//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpopZtation
{
    using System;
    using System.Collections.Generic;
    
    public partial class msCart
    {
        public int CustomerID { get; set; }
        public int AlbumID { get; set; }
        public int Quantity { get; set; }
    
        public virtual msAlbum msAlbum { get; set; }
        public virtual msCustomer msCustomer { get; set; }
    }
}
